imap:
  web-alert:
    username: 'webalerts@patyk.cz'
    host: 'mail.patyk.cz'
    port: 143
    password: 'someStrongPassword'

kafka:
  brokerIp: '192.168.168.168'
  brokerPort: 9092
  topic: 'general-imap-topic'